name: unzip

on:
  workflow_dispatch:
    inputs:
      unzip:
        description: "unziper"
        required: true
        type: boolean
    
jobs:
  unzip:
    runs-on: ubuntu-latest
    
    steps:
    - name: CheckOut
      uses: actions/checkout@v4

    - name: InstallDepends
      shell: bash
      run: |
        sudo apt-get install -y tree fontforge python3

    - name: DownloadFile
      shell: bash
      run: wget -O zip.zip $(cat link)

    - name: Unzip
      shell: bash
      run: |
        unzip zip.zip -d unziped
        tree
        du -ah
        ls -ltrah

    - name: ChechSum
      shell: bash
      run: |
        wget -O 2 "./unziped/SubsetOTF/CN/SourceHanSansCN-Regular.otf"
        md5sum 2 ./unziped/SubsetOTF/CN/SourceHanSansCN-Regular.otf

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: MapleMono-NF-CN-Medium
        path: unziped/MapleMono-NF-CN-Medium.ttf







