name: unzip

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      unzip:
        description: "unziper"
        required: true
        type: boolean
    
jobs:
  unzip:
    runs-on: ubuntu-latest
    
    steps:
    - name: CheckOut
      uses: actions/checkout@v4

    - name: InstallDepends
      shell: bash
      run: |
        sudo apt-get install -y tree fontforge python3
        pip install fonttools

    - name: DownloadFile
      shell: bash
      run: |
        wget -O SourceHanSansCN-Regular.otf $(cat link)
        wget -O ios.zip "https://github.com/5hes/Iosevka_fork/actions/runs/11993078204/artifacts/2229042294"

    - name: otf2ttf
      shell: bash
      run: |
        unzip ios.zip && rm ios.zip
        pyftinfo SourceHanSansCN-Regular.otf
        fontforge -script remove_hinting.pe
        ls -ltrah
        fontforge -script 2ttf.pe SourceHanSansCN-Regular.otf SourceHanSansCN-Regular.ttf
        fontforge -script merge_fonts.pe
        ls -ltrah

        
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: bestfont
        path: Merge.ttf







