name: unzip

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      unzip:
        description: "unziper"
        required: true
        type: boolean
    
jobs:
  unzip:
    runs-on: ubuntu-latest
    
    steps:
    - name: CheckOut
      uses: actions/checkout@v4

    - name: InstallDepends
      shell: bash
      run: |
        sudo apt-get install -y tree fontforge python3
        pip install fonttools

    - name: DownloadFile
      shell: bash
      run: |
        wget -O SourceHanSansCN-Regular.otf $(cat link)
        wget -O ios.zip "https://productionresultssa9.blob.core.windows.net/actions-results/3458e38a-e6a1-48d9-9d30-2790d177bbee/workflow-job-run-06bc8c09-0a70-5034-2452-3d74bb2a1e94/artifacts/2101b0eb9a8083ce9de615b96e7f77774ca2d06b472c059d0ad0b1d3f2c99c93.zip?rscd=attachment%3B+filename%3D%22jb-400-monoterm.zip%22&se=2024-11-24T14%3A37%3A43Z&sig=jBSFX5yVaqYo2HIEel7V2CoPRoA3LfZRRmc4UgnrO7A%3D&ske=2024-11-24T23%3A58%3A25Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2024-11-24T11%3A58%3A25Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2024-11-04&sp=r&spr=https&sr=b&st=2024-11-24T14%3A27%3A38Z&sv=2024-11-04"

    - name: otf2ttf
      shell: bash
      run: |
        ls -ltra
        unzip ios.zip && rm ios.zip
        python -m fontTools.ttLib.ttInfo SourceHanSansCN-Regular.otf
        fontforge -script remove_hinting.pe
        ls -ltra
        fontforge -script 2ttf.pe SourceHanSansCN-Regular.otf SourceHanSansCN-Regular.ttf
        fontforge -script merge_fonts.pe
        ls -ltra

        
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: bestfont
        path: Merge.ttf







